export { PathsToPage, social, navLink } from './router';
export {
  searchTextDef,
  localKeyText,
  noRating,
  arrRating,
  detailedInfo,
  apiUrl,
  feedbackBtn,
  error,
  cardDateOptions,
  feedbackDateOptions,
  registrationForm,
  authorizationForm,
  recoveryForm,
  registrationSuccess,
  registrationErrorUnique,
  registrationError,
  authorizationError,
} from './constants';
